name: 'deploy greetings application'
inputs:
  environment:
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "Deployment triggered on ${{ inputs.environment }} environment.."
      shell: bash
    - name: stop container
      run: docker-compose stop greetings-app-${{ inputs.environment }}
      shell: bash
    - name: remove container
      run: docker-compose rm greetings-app-${{ inputs.environment }}
      shell: bash
    - name: run container
      run: docker-compose up -d greetings-app-${{ inputs.environment }}
      shell: bash